---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name: "{{ rpi_default_packages }}"
    state: present

- name: Create Python virtualenv and install packages
  pip:
    virtualenv: "{{ rpi_python_virtualenv }}"
    name: "{{ item }}"
  with_items: "{{ rpi_python_packages }}"
  when: rpi_create_python_virtualenv
