#/boot/firmware/cmdline.txt
# console=serial0,115200 console=tty1 root=PARTUUID=0c78c6e2-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=JP cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
---
- name: "{{ 'Enable' if rpi_spi else 'Disable' }} SPI"
  replace:
    path: "{{ rpi_boot_cmdline_file_path }}"
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'

  loop: "{{ rpi_boot_cmdline }}"
#  notify: reboot
